version: "3.9"

services:
  solarpanels_db:
    image: postgres
    networks:
      cloud-solarpanels:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: solarpanels
    volumes:
      - "${PERSISTENT_DB_PATH:-.}/solarpanels_db:/var/lib/postgresql/data"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 600M
  mqtt_adapter:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      cloud-solarpanels:
    restart: unless-stopped
    depends_on:
      - "solarpanels_db"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 600M
  cbroker:
    image: eclipse-mosquitto
    networks:
      cloud-solarpanels:
      ingress:
    volumes:
      - "${PERSISTENT_DB_PATH:-.}/mosquitto/data:/mosquitto/data"
      - "${PERSISTENT_DB_PATH:-.}/mosquitto/config:/mosquitto/config"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 600M
  pgadmin:
    image: dpage/pgadmin4
    networks:
      cloud-solarpanels:
    restart: unless-stopped
    ports:
      - 127.0.0.1:8088:5050
    volumes:
      - "${PERSISTENT_DB_PATH:-.}/pgadmin:/var/lib/pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=FSD9iw8S89FwlPm
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_LOGIN_BANNER="Authorised users only!"
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
      - PGADMIN_LISTEN_PORT=5050
    logging:
      driver: none

networks:
  cloud-solarpanels:
  ingress:
    external: true
