version: "3.9"

services:
  edge_rasp:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      edge-solarpanels:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 600M
  broker:
    image: eclipse-mosquitto
    networks:
      edge-solarpanels:
    volumes:
      - "${PERSISTENT_DB_PATH:-.}/mosquitto/data:/mosquitto/data"
      - "${PERSISTENT_DB_PATH:-.}/mosquitto/config:/mosquitto/config"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 600M

networks:
  edge-solarpanels:
