version: "3"

services:
  edge_rasp:
    ports:
      - 10.0.100.1:5683:5683/udp
    environment:
      - VIRTUAL_HOST=rasp-edge
      - VIRTUAL_PORT=8080
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 600M
    depends_on:
      - broker
  broker:
    image: eclipse-mosquitto
    volumes:
      - "${PERSISTENT_DB_PATH:-.}/mosquitto/data:/mosquitto/data"
      - "${PERSISTENT_DB_PATH:-.}/mosquitto/config:/mosquitto/config:ro"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 600M
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "${PERSISTENT_DB_PATH:-.}/nginx-certs:/etc/nginx/certs"
